AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'spec/**/*'